### ISSUE TITLE
Error in mnistGenerator classes

### ISSUE THREAD

**Issue by wykang** [nvcuong/variational-continual-learning#1]
Hi, if i am correct, I found a critical problem on your code.

The problem is in the run_split.py -SplitMnistGenerator()
In the classes, it vertically stacks two labels of data without data shuffling. As a result, when we call coreset_method() in vcl.py- run_vcl(), it may sample only one label of data if the coreset size is small. 

Can you check this problem?
Thanks

**Comment by nvcuong** [comment]
Hi @wykang, there is no problem with that. Both coreset functions in [coreset.py](https://github.com/nvcuong/variational-continual-learning/blob/master/ddm/alg/coreset.py) do not need the data to be shuffled.

**Comment by wykang** [comment]
Thanks, I misunderstood the task setting for this algorithm. Now, I got it.
