### ISSUE TITLE
Different result when running run_split.py

### ISSUE THREAD

**Issue by rymane** [nvcuong/variational-continual-learning#5]
When running run_split.py I get a different result from the one in your README file. I have tried several times and I get the same result each time. Do you know the reason for this?

![split](https://user-images.githubusercontent.com/60221527/80357805-c96de980-887b-11ea-883f-b8123b356333.jpg)

**Comment by nvcuong** [comment]
Hi @rymane,

It could be because of the Tensorflow version. Can you make sure to run with Tensorflow 1.4.0?

Besides, for more reliable results, we should run the code several times with different random seeds and then average the curves.
